export const ANNOUNCEMENT_LIST_REQUEST = 'ANNOUNCEMENT_LIST_REQUEST';
export const ANNOUNCEMENT_LIST_SUCCESS = 'ANNOUNCEMENT_LIST_SUCCESS';
export const ANNOUNCEMENT_LIST_FAIL = 'ANNOUNCEMENT_LIST_FAIL';

export const ANNOUNCEMENT_CREATE_REQUEST = 'ANNOUNCEMENT_CREATE_REQUEST';
export const ANNOUNCEMENT_CREATE_SUCCESS = 'ANNOUNCEMENT_CREATE_SUCCESS';
export const ANNOUNCEMENT_CREATE_FAIL = 'ANNOUNCEMENT_CREATE_FAIL';

export const ANNOUNCEMENT_DETAILS_REQUEST = 'ANNOUNCEMENT_DETAILS_REQUEST';
export const ANNOUNCEMENT_DETAILS_SUCCESS = 'ANNOUNCEMENT_DETAILS_SUCCESS';
export const ANNOUNCEMENT_DETAILS_FAIL = 'ANNOUNCEMENT_DETAILS_FAIL';

export const ANNOUNCEMENT_UPDATE_REQUEST = 'ANNOUNCEMENT_UPDATE_REQUEST';
export const ANNOUNCEMENT_UPDATE_SUCCESS = 'ANNOUNCEMENT_UPDATE_SUCCESS';
export const ANNOUNCEMENT_UPDATE_FAIL = 'ANNOUNCEMENT_UPDATE_FAIL';

export const ANNOUNCEMENT_DELETE_REQUEST = 'ANNOUNCEMENT_DELETE_REQUEST';
export const ANNOUNCEMENT_DELETE_SUCCESS = 'ANNOUNCEMENT_DELETE_SUCCESS';
export const ANNOUNCEMENT_DELETE_FAIL = 'ANNOUNCEMENT_DELETE_FAIL';
