// Event creation constants
export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_FAIL = 'EVENT_CREATE_FAIL';
export const EVENT_CREATE_RESET = 'EVENT_CREATE_RESET';

// Event list constants
export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST';
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL';

// Event details constants
export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST';
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS';
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL';

// Event update constants
export const EVENT_UPDATE_REQUEST = 'EVENT_UPDATE_REQUEST';
export const EVENT_UPDATE_SUCCESS = 'EVENT_UPDATE_SUCCESS';
export const EVENT_UPDATE_FAIL = 'EVENT_UPDATE_FAIL';
export const EVENT_UPDATE_RESET = 'EVENT_UPDATE_RESET';

// Event delete constants
export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST';
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL';

// Event approval constants
export const EVENT_APPROVE_REQUEST = 'EVENT_APPROVE_REQUEST';
export const EVENT_APPROVE_SUCCESS = 'EVENT_APPROVE_SUCCESS';
export const EVENT_APPROVE_FAIL = 'EVENT_APPROVE_FAIL';

// Event rejection constants
export const EVENT_REJECT_REQUEST = 'EVENT_REJECT_REQUEST';
export const EVENT_REJECT_SUCCESS = 'EVENT_REJECT_SUCCESS';
export const EVENT_REJECT_FAIL = 'EVENT_REJECT_FAIL';

// Pending events list constants
export const EVENT_PENDING_LIST_REQUEST = 'EVENT_PENDING_LIST_REQUEST';
export const EVENT_PENDING_LIST_SUCCESS = 'EVENT_PENDING_LIST_SUCCESS';
export const EVENT_PENDING_LIST_FAIL = 'EVENT_PENDING_LIST_FAIL';

// User events list constants
export const EVENT_USER_LIST_REQUEST = 'EVENT_USER_LIST_REQUEST';
export const EVENT_USER_LIST_SUCCESS = 'EVENT_USER_LIST_SUCCESS';
export const EVENT_USER_LIST_FAIL = 'EVENT_USER_LIST_FAIL';

// Admin events list constants
export const EVENT_ADMIN_LIST_REQUEST = 'EVENT_ADMIN_LIST_REQUEST';
export const EVENT_ADMIN_LIST_SUCCESS = 'EVENT_ADMIN_LIST_SUCCESS';
export const EVENT_ADMIN_LIST_FAIL = 'EVENT_ADMIN_LIST_FAIL'; 